module.exports = {
    browsersync: '[Parent Task] Loads the site in the default browser and runs a server for other devices to connect to.',
    build: '[Parent Task] Processes files used to create the site and opens it in the default browser.',
    clean: '[Parent Task] Deletes all files and folders generated by Gulp.',
    vendor: '[Parent Task] Copies vendor code from `node_modules/`.'
};
